using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RosalindProblems
{
    public class MainClass
    {
        public static void Main(string[] args)
        {
            //int[] arr = RosalindProblems.DNA_Nucleotides.FirstProblem("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
            //int[] arr = RosalindProblems.DNA_Nucleotides.FirstProblem("CGTATGCAGAGGATATGGGTGGATCGCCCACGACTTATAATGGAGGCTCAGGCAGCTGCTACCCGCATCCCTCCCCGTTATTAGGGGGACCAATACTCCGGCCAGACAGTTGATTGTAATCATAATAATCAAAAAGAAATACTGATACCCCTCAACTCGAAGATTCGTAACGACCTGCAGATAGTGTAGATAGAATCCCATTTGCACGAAACAAGGGAGCCCAACCATGCAAATATATCGAGGCCTTACTCTTAGCTGTTAACGGCAAGGCCACTCCTAGTCGACAATCGACTAACACTCGGGGATGCGGTAAATTCAAAGGTGCCTATAACCCCGCGAGTATTAGGGTACCTCCTCGGACCTTCCTGAGCGAATGAATGGTAAACCAGCCTAAGAGGTGATGGCGAGAATACACTGAATTCTGGTCTGCATGTTTGGAGCCATTGGTCGCTCTACCTTGGTCCCTTAATTGGGAAGCCGGAGTTGGTCGGATTTGCTCTGTTAATCCTTGGCTTCCATGTTTACGCGCAGCCACGGTATCCACGAAACCTTTGCATTCGGGACGGATGTGTAGAAAGGAAAAATCGAGCGAGTCGTGCTGACCCGTATAATGGTGAAAAGACAGAATAGAGTGGTTTTATCCACCCTGACTACCCATTTGAGTCCCGGAACCTCAATTCGCAGCTTTGATGGAGACCATCACCCTAAGCCGAGTTCCAGGGAATCACCCCCTGAGTTGTGACGATGTAAGAGGGGTCCTTGAGACTCTCGAAGAAGCTATGTGATTGCTTATGGCGCAGTCAATGTGCTGCAGGTCTCTTCAAAATCAATCGAACGTGCGAAATACGTCAACGACAG");
            //int[] arr = RosalindProblems.DNA_Nucleotides.FirstProblem1("CGTATGCAGAGGATATGGGTGGATCGCCCACGACTTATAATGGAGGCTCAGGCAGCTGCTACCCGCATCCCTCCCCGTTATTAGGGGGACCAATACTCCGGCCAGACAGTTGATTGTAATCATAATAATCAAAAAGAAATACTGATACCCCTCAACTCGAAGATTCGTAACGACCTGCAGATAGTGTAGATAGAATCCCATTTGCACGAAACAAGGGAGCCCAACCATGCAAATATATCGAGGCCTTACTCTTAGCTGTTAACGGCAAGGCCACTCCTAGTCGACAATCGACTAACACTCGGGGATGCGGTAAATTCAAAGGTGCCTATAACCCCGCGAGTATTAGGGTACCTCCTCGGACCTTCCTGAGCGAATGAATGGTAAACCAGCCTAAGAGGTGATGGCGAGAATACACTGAATTCTGGTCTGCATGTTTGGAGCCATTGGTCGCTCTACCTTGGTCCCTTAATTGGGAAGCCGGAGTTGGTCGGATTTGCTCTGTTAATCCTTGGCTTCCATGTTTACGCGCAGCCACGGTATCCACGAAACCTTTGCATTCGGGACGGATGTGTAGAAAGGAAAAATCGAGCGAGTCGTGCTGACCCGTATAATGGTGAAAAGACAGAATAGAGTGGTTTTATCCACCCTGACTACCCATTTGAGTCCCGGAACCTCAATTCGCAGCTTTGATGGAGACCATCACCCTAAGCCGAGTTCCAGGGAATCACCCCCTGAGTTGTGACGATGTAAGAGGGGTCCTTGAGACTCTCGAAGAAGCTATGTGATTGCTTATGGCGCAGTCAATGTGCTGCAGGTCTCTTCAAAATCAATCGAACGTGCGAAATACGTCAACGACAG");

            /*foreach (int i in arr)
            {
                Console.Write("{0} ", i);
            }
            Console.ReadKey();*/

            //String str = RosalindProblems.DNA_to_RNA.SecondProblem("GATGGAACTTGACTACGTAAATT");
            //String str = RosalindProblems.DNA_to_RNA.SecondProblem1("ATTTGGACCCGAACGAGCCGCCGATGCGCCAGGTTTACAACAGGCTAATCCATTACTACCGAGCGATACGTTACCGAAAACAGCCCCCCAGTAGACGCGTGCAGCCACCTGACGCAGGACGTTACGATACTCTTATATGCACGTTAATTGCTTTATCTGTGCTGCGACAGTCATCCTTGTACTACCGATCGAAGTCAACGATAACCTTCGGTTCGGCATGATCACAGGTGTTTGTATCCCACTGCTGTTCCGTGTACCGTTTACGCAATCGGTGCGACGCAAGCACGCTAAGATGCGAAAGAGTACATGTCCGTTTTCAATTGCGAGGCGATAATCCGGGTGCCGGGGCTGTCGTGAGGATTTAGCTGGTGCCCTATAGGCGCTGACTTTTTCGGCGCGCGTGATTGCTTTACATAACCGATTACAGCCAGCCTCTCTCGTTAACTAAGTGTTATTACGTGGGATCCAGCTTAGGAGGCGCCTCTTATGACTAGATCGGGTTATATCGCCCCCTAACTTAACCATAAAGCTTACACATGTGTTAGCATAATATCTAAGGGATCCCCAGTACCAGCTGGAACCAACGAATTTCCAAGGATAGATTTTGAGCTAATCTTAAACCCTTGGGTGGAGAGTACCCCGCGTGGAGTGACGCAGGGTCCACACGCCGGCCAGTACCGGTAGAAATACTCCTTAAGGAATCACAACATTCCTATGTTCCATTTTCAATCTCATTCTAGTAGTAAATACTCATGAGCAGTGAAAAGGGTGTAGGCGGAGTTAATTCATATTCCACTAATAAAGGCTCTGGCGCCGTATAAAAGGACTTTGTTAAGGGAATGGTCGGGACGGGTTAATGCGCTTGGGTCACGGCTATATCTCTTATGCTATTCGTGGTTGGATTGACGGTTCGCGAGGTGGAATGGTTTTGGTGTTGAGAGGGGATGA");
            //StreamWriter sw = new StreamWriter("txt.txt");
            //sw.WriteLine(str);
            //sw.Close();
            //Console.WriteLine(str);
            //Console.ReadKey();

            //String str = RosalindProblems.DNA_Complement.ThirdProblem("AAAACCCGGT");
            //String str = RosalindProblems.DNA_Complement.ThirdProblem("CTGGGGTCACACTCCTTCCATAGAAAATATCTCCGTTCTAGCGGGAAGCTAGAGGTCACACTACTGACGTCGTCAAAGAGTGCCAAAAGCGACTCAATGACAGTTCACCGGTCGCAGTCGCGTCTCAGTGCGATGTCTGCCGGGCCTGCGCCCCCGGCATAAGAACCTCGTCGTCGCGCGCGGACACATCAAGACCTTATACGATTTTATGAGGACAGCTCGAGCTCTCCCACTCTTTTATACGGAGCTCCAAGGTTTAGTAGATGTATAATTACCACGCGTAAAAGTACATTCCATGCTATACCGGCACCCTTGGTCCCTTGTACGCTTAACCGTCAACGGTATTCTTAAACTTTCACGGTATGTCCTCCTGGGGTTACAAACTTCCAGACTTCTTGGCACATAGATCAGGGGTTGATACTCAGTTTTATCTTGCCCCTCGTTTGTGGGGCAATGGACTCTTCACTGCCAGACTTACTCGACAGGTGTGTAAGGACACATTGAGCCTGGCATCTTCCTTCACTGATATAGGCGCCGGAGGTTCCCAACTTTCAAATTGTGTTGATGCCTAAAAGATCGCGTATGACTTTGCAGGCCCCTGTACGGATGCCTGTACGAGTGCCCAATAAGTTCCTTACGATTACCGCGACTTATAATTTGTACATAAGCTCCACGCTTTGCTGCCGCTAGTGAGATCGCGCCACGCTGTAGAGCTGGGCAAGTTGAGGGTCTTAGTAACAATTGCGCATGGGAGTAGCGATTGTGTTCCACCAAGGGTATGCTAAAGACCAAAGTCCTTGTAACGAAGTCTAGAGTACCTGGGTTCCAGCGCCGCTGTCGCCACCGACCAAACGGTACTGACGTTCTCATTCGATTTAGAGCAGAAATGGTATCTTTCCCTGAGACGCCTCGTCCAATGTCGGGCTT");
            //StreamWriter sw = new StreamWriter("txt.txt");
            //sw.WriteLine(str);
            //sw.Close();

            //String str = RosalindProblems.GC_Content.FourthProblem("C:\\Users\\gekka_000\\Documents\\Visual Studio 2012\\Projects\\ConsoleApplication2\\ConsoleApplication2\\rosalind_gc.txt");
            //Console.WriteLine(str);

            //Console.WriteLine(RosalindProblems.Rabbits_Fibonacci.calculateRabbits(5, 3));
            //Console.WriteLine(RosalindProblems.Rabbits_Fibonacci.calculateRabbits(33, 5));

            //Console.WriteLine(RosalindProblems.PointMutations_Hamming.calculateHammingDistance("GAGCCTACTAACGGGAT", "CATCGTAATGACGGCCT"));
            //Console.WriteLine(RosalindProblems.PointMutations_Hamming.calculateHammingDistance("CCAGATGAGTATGCAGCCAGCAGTGACCTGAAACGCTTCATGTGCCTTAGACCAGGAGCCACGACCCTGAGCATGAAGACTAAAGCTATTTTCGCAGCGGAACACGCCTAGTACCGCAACGTAAAATAATTAACTATGGTGTGTGTTCACCACCTGTCGAGCCCTAGCGCGTACGTTCCAGTCCTTTATTTATATAACACTAGTCGATGCGGGGCTGGGCGCGACACCCTCCGATATCCCTTATGGTGGAAAACTTGCTCTTGAGGGATATAGTGTCCCGGGTTGTGTCTGATCCCGCCATAACAGCCGACTAGGAGGTGGAGTAGATCCCTCATGCATGTAAGGCATCTATTCGGCGGGCCGAGACTTCATGTGGAGACGCACGTAACACTTCAACTGCATACTGGAAGTGTACCTGACTGTCGTTATACGCAGATGGACCCCTTCTGATCAGAAGCGTTCAATTTTGAAGCGGTAACCTGTTCGGGCATTTAAGTTGCCACCGAACTAACGGATCACCCCATGGTGCATCGATATAATTATTCATCAATGAGAGTTGCTAGTAAATCCCTGCCAGGTGCGAATTTCCTGTGCAGATCCAACAGCTCAGACGCGGCGGATGGAGAGGCGACCTCATTCATCCATGAGGTACCCGGACAAACTCTGATCCCGTGTGGGTGAGCGTATTAACCTCGACCTCGGCGACGCGTCCACGAATCATTTCAACTGTATCAGTCTATCGCTCTATGTAGCTCAGTAGGTGGGTTGAACACCCTATCAGCGCGATTTGTCCGCACACCTAAGTGACAAGGTTAAATATCTGTTGAGGGCCTGCCCTGGATCGAGCTGTACGAACTTTCTTCCTTTTCACGTGGAACTGACGACGGGGCCACCAGGACGGGGAGTTTCTGGTACCTGTACCACCATATACAGCTTTAGAC", "TCCGATTCAGGTAATACAAGAATTCACCCGTCGAACTCCCACTGCCTTACTCCGTAAACCACCGATCTAATCATATACAGTCCAACGCTATTCTCAGTGAACAACGCCTGAACCCAGAATATTGAACAAGTGTCATGTGAAGATCGTTATTCCATATAGGGTCCTATATCGGTGGGTTCACCGATATATCTGTTTAGCACTTTTGGACGCGGGCCTCACGAAGACTTGCGTGAACATAGCTTTGTGTGGCTGACTTGCTTTTGCGGGATATTATGTCCCGGGAAACGCCTGAAGCCGCGGTGACAGGTGAAGAATAGTTTGAGGCTGTCCCTCATGCCACTCATGTGTCCAATCCACTGCCCTGGACATAATGACTACTCGCACGTAGCACCGTAGAACCTTTGTGAACGAGCATCTGACTAATGTAAGTATCCACTCGGCCCGGTCAGTTATCAGGTCATCCATCATGACGCCAGAACAGGCTTTCGCATTAAAGGAGTCTGAGAATGAACTCTATACCCGACGCCACATCGAGTTAATTATCGCTCAATGCAAATCTCTATGAATTCCTGAATTAGTCCGTTATCGACGTTCAGTCCCTACAGCGCCGTCGGTGTTAATATAGAATCCCCTTGCTTTCTTCGCCTGGACTCAAGAAAACAAACTATGGACGCGGTGTGCGGCTAGGCGACTTAACCTCCCCCGTTCAGCCACCCATGTTCTACCCGGGATAGGTCCATCGCTTTGTCAGTGAAACTTTGTGGGTTCCGTAGCCTATAAGGAGGGATTCTGCGTGTCTATGAGTAACGCGGTGATCTATCTGGTTAGGCCCGACCCTGGATTCCGGTAGCATCACGTGCGAGCTTTTGATTGCCAAATGGGCGCTGAGCCACCGCGCCGAGTTATTTCGGCAACCTTGAGTACGATGCACAGATGAAGAC"));
            
            List<string> arr = RosalindProblems.Rearrangements_Genomic_Changes.recursive(7);

            foreach (string i in arr)
            {
                Console.Write("{0} \n", i);
            }

            Console.ReadKey();
        }
    }
}
